### ISSUE TITLE
Launchpad review

### ISSUE THREAD

**Issue by akshay-ap** [oceanprotocol/marketplace-launchpad#34]
## Suggestions:

- [x] Inconsistent use of word `white label`
<img src="https://user-images.githubusercontent.com/16358982/168871272-4ff98fd6-354d-4187-8590-2287dca2bbcb.png" width="200" />

- [x] Missing link
<img src="https://user-images.githubusercontent.com/16358982/168888445-e2a64716-0121-4318-9b93-98eeecb0dd9c.png" />

- [x] May be `Turing-complete`?
<img src="https://user-images.githubusercontent.com/16358982/168889799-1a5d1f5c-2a0b-47ad-af1b-fca12eafda20.png" />

- [x] May be highlight first word of each type of limilation by making them bold?
<img src="https://user-images.githubusercontent.com/16358982/168890393-410e205b-37d4-4d6e-90ab-b85f4c8ba209.png" />

- [x] May be add a sentence on free pricing as well?
Use case: Publishing open-source datasets with licenses that mandate the data to be free

![img-4](https://user-images.githubusercontent.com/16358982/168896194-18805915-0355-4489-baf7-801fbf03a03b.png)

- [x] Fix this sentence:
![img-5](https://user-images.githubusercontent.com/16358982/169024910-ac7171a9-bb6c-400e-8249-d1a105595bf3.png)

- [x] Missing image?
![img-6](https://user-images.githubusercontent.com/16358982/169027558-a53670e5-5229-46f8-9cdb-665f2314d984.png)

- [x] Missing link?
![img-7](https://user-images.githubusercontent.com/16358982/169274580-2d4a162e-723e-4175-a222-5c79c11fbea5.png)

- [x] Other minor spelling, grammar issues

**Comment by jamiehewitt15** [comment]
Great, thanks a lot for the review and for giving this feedback. They are all good points that can be fixed.

Are you working on these changes? If so, can you assign the issue to yourself?

**Comment by akshay-ap** [comment]
Yes, I can fix those.
Regarding "Missing image" can you provide some details on what to add there? just a screenshot or can we add reference to here https://docs.oceanprotocol.com/tutorials/marketplace-download-data-asset/ ?

**Comment by jamiehewitt15** [comment]
Yeah, I'd actually remove the bit about an image and send them to that tutorial in the docs instead. There is no point having duplicate content 

This image may be useful in the section about datatokens but we would have to explain its relevance:
![image](https://user-images.githubusercontent.com/20739535/169068937-5292d7f0-2f8f-4fd2-9f50-2aa1a7dd981d.png)
