### ISSUE TITLE
Missing page

### ISSUE THREAD

**Issue by akshay-ap** [oceanprotocol/marketplace-launchpad#36]
**Describe the bug**
Marketplace reports 404

**To Reproduce**
1. Go to https://marketplace-launchpad.surge.sh/en/setup/module-0/
2. See error
OR:
1. Go to https://marketplace-launchpad.surge.sh/
2. Click `Enterprise` (https://marketplace-launchpad.surge.sh/en/enterprise)
3. Scroll till bottom
4. Click `Begin`

![image](https://user-images.githubusercontent.com/16358982/169035212-d1d36104-0d68-4bad-8b02-ece0411d643d.png)

**Expected behavior**
Page exists or the link is removed

**Comment by jamiehewitt15** [comment]
Yeah, we just need to remove the "Begin" link here that doesn't lead anywhere so shouldn't be there
