### ISSUE TITLE
404 page error on the marketplace quickstart guide links

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/marketplace-launchpad#37]
All the links from the marketplace quickstart guide give a 404 error

<img width="1008" alt="Screenshot 2022-05-19 at 10 57 25" src="https://user-images.githubusercontent.com/84312885/169242958-9bd18771-678d-42e6-99de-975223b8f440.png">

<img width="1273" alt="Screenshot 2022-05-19 at 10 58 33" src="https://user-images.githubusercontent.com/84312885/169243097-e75af6d2-e8be-4d28-b6bd-55f02250cc40.png">

**Comment by jamiehewitt15** [comment]
Thanks for testing it out, I'll fix this
