### ISSUE TITLE
Rename section `User flows` to `Publishing and pricing`

### ISSUE THREAD

**Issue by akshay-ap** [oceanprotocol/marketplace-launchpad#39]
## Description

The page https://marketplace-launchpad.surge.sh/en/setup/module-1/user-flows has title `User flows`. It is mainly focused on publishing and asset pricing. Ocean has various flows like Publish, download, run C2D. 
Instead of using term `User flows`, I think it `Publishing and pricing` or `Publish flows` is appropriate title for the page.

**Comment by jamiehewitt15** [comment]
Yeah good point, it's only really the publish flow that is described here. I would suggest going with `Publish Flow` to keep it short
